{{- if .Values.job.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook.jobServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "webhook.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "webhook.jobServiceAccountName" . }}
  labels:
{{ include "webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
# You need to already have a ClusterRole named "secret-reader".
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook.jobServiceAccountName" . }}
  labels:
{{ include "webhook.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.jobServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "webhook.jobServiceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "webhook.jobServiceAccountName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
# You need to already have a ClusterRole named "secret-reader".
kind: RoleBinding
metadata:
  name: {{ include "webhook.jobServiceAccountName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "webhook.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.jobServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "webhook.jobServiceAccountName" . }}-secret
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
