apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook.configMapName" . }}
  namespace: {{ .Release.Namespace }}
data:
  rewrite-config.yaml: |
    {{- toYaml .Values.rewriteConfig | nindent 4 }}
