apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-rewrite-webhook-job
  namespace: image-rewrite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-rewrite-webhook-job
rules:
  - apiGroups:
     - "certificates.k8s.io"
    resources:
     - "certificatesigningrequests"
     - "certificatesigningrequests/approval"
    verbs:
     - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-rewrite-webhook-job
subjects:
  - kind: ServiceAccount
    name: image-rewrite-webhook-job
    namespace: image-rewrite
roleRef:
  kind: ClusterRole
  name: image-rewrite-webhook-job
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-rewrite-webhook-job-secret
  namespace: image-rewrite
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-rewrite-webhook-job-secret
  namespace: image-rewrite
subjects:
  - kind: ServiceAccount
    name: image-rewrite-webhook-job
    namespace: image-rewrite
roleRef:
  kind: Role
  name: image-rewrite-webhook-job-secret
  apiGroup: rbac.authorization.k8s.io
