apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: image-rewrite-webhook
webhooks:
- name: image-rewrite.toolkit.ibm
  clientConfig:
    service:
      name: image-rewrite-webhook
      namespace: image-rewrite
      path: "/mutate"
    caBundle: ""
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
